# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: weather_forecast_app_development

test:
  <<: *default
  database: weather_forecast_app_test

production:
  <<: *default
  database: weather_forecast_app_production
  username: weather_forecast
  password: <%= ENV["WEATHER_FORECAST_DATABASE_PASSWORD"] %>
